apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
  namespace: elad
spec:
  scaleTargetRef:
    name: interview-assignment-app-chart
  triggers:
  - type: cpu
    metadata:
      type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      value: "50"
  - type: cpu
    metadata:
      type: AverageValue # Allowed types are 'Utilization' or 'AverageValue'
      value: "50"