apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: simple-web-scaledobject
  namespace: elad
spec:
  scaleTargetRef:
    name: interview-assignment-app-chart
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicas: 1
  maxReplicas: 5
  triggers:
  - type: cpu
    metadata:
      type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      value: "60"
  - type: memory
    metadata:
      type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      value: "60"
  - type: cron
    metadata:
        timezone: Israel
        start: 0 8 * * *       
        end: 0 12 * * *
        desiredReplicas: "5"